'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Map\Defas.def")>  _
        Public Property myDefaFileName() As String
            Get
                Return CType(Me("myDefaFileName"),String)
            End Get
            Set
                Me("myDefaFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Map\KHData.udl")>  _
        Public Property myCacKyHieuUDL() As String
            Get
                Return CType(Me("myCacKyHieuUDL"),String)
            End Get
            Set
                Me("myCacKyHieuUDL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Bản đồ tác chiến")>  _
        Public Property myTenCT() As String
            Get
                Return CType(Me("myTenCT"),String)
            End Get
            Set
                Me("myTenCT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property myHienDanhSach() As Boolean
            Get
                Return CType(Me("myHienDanhSach"),Boolean)
            End Get
            Set
                Me("myHienDanhSach") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Map\BanDo.gst")>  _
        Public Property myMapGst() As String
            Get
                Return CType(Me("myMapGst"),String)
            End Get
            Set
                Me("myMapGst") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Map\BanDoNho.gst")>  _
        Public Property myMapNhoGst() As String
            Get
                Return CType(Me("myMapNhoGst"),String)
            End Get
            Set
                Me("myMapNhoGst") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("312")>  _
        Public Property mySoPixelsPer1000m() As UInteger
            Get
                Return CType(Me("mySoPixelsPer1000m"),UInteger)
            End Get
            Set
                Me("mySoPixelsPer1000m") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3357")>  _
        Public Property myKHQSZoom() As UInteger
            Get
                Return CType(Me("myKHQSZoom"),UInteger)
            End Get
            Set
                Me("myKHQSZoom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1020")>  _
        Public Property myKHQSMWidth() As UInteger
            Get
                Return CType(Me("myKHQSMWidth"),UInteger)
            End Get
            Set
                Me("myKHQSMWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property myTinhChinhGocQuay() As Double
            Get
                Return CType(Me("myTinhChinhGocQuay"),Double)
            End Get
            Set
                Me("myTinhChinhGocQuay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Map\LongThanh.jpg")>  _
        Public Property myTextureFile() As String
            Get
                Return CType(Me("myTextureFile"),String)
            End Get
            Set
                Me("myTextureFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("312")>  _
        Public Property my3DSoPixelsPer1000m() As UInteger
            Get
                Return CType(Me("my3DSoPixelsPer1000m"),UInteger)
            End Get
            Set
                Me("my3DSoPixelsPer1000m") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("106.9418258")>  _
        Public Property myMap1X() As Double
            Get
                Return CType(Me("myMap1X"),Double)
            End Get
            Set
                Me("myMap1X") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10.8443307")>  _
        Public Property myMap1Y() As Double
            Get
                Return CType(Me("myMap1Y"),Double)
            End Get
            Set
                Me("myMap1Y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("107.0017013")>  _
        Public Property myMap2X() As Double
            Get
                Return CType(Me("myMap2X"),Double)
            End Get
            Set
                Me("myMap2X") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10.7747964")>  _
        Public Property myMap2Y() As Double
            Get
                Return CType(Me("myMap2Y"),Double)
            End Get
            Set
                Me("myMap2Y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Map\GridData.txt")>  _
        Public Property myGridDataFile() As String
            Get
                Return CType(Me("myGridDataFile"),String)
            End Get
            Set
                Me("myGridDataFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("101")>  _
        Public Property myGRID_WIDTH() As UInteger
            Get
                Return CType(Me("myGRID_WIDTH"),UInteger)
            End Get
            Set
                Me("myGRID_WIDTH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("119")>  _
        Public Property myGRID_HEIGHT() As UInteger
            Get
                Return CType(Me("myGRID_HEIGHT"),UInteger)
            End Get
            Set
                Me("myGRID_HEIGHT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4.5")>  _
        Public Property mySCALE_FACTOR() As Single
            Get
                Return CType(Me("mySCALE_FACTOR"),Single)
            End Get
            Set
                Me("mySCALE_FACTOR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Map\D3DModelMesh.xml")>  _
        Public Property myFlag3DsFile() As String
            Get
                Return CType(Me("myFlag3DsFile"),String)
            End Get
            Set
                Me("myFlag3DsFile") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.BdTC.My.MySettings
            Get
                Return Global.BdTC.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
